#1: Complete project base
Flash1ee/collector-telegram-bot pull request #13
Opened 2023-04-28 19:54 UTC by prianechka

Было выполнено:
1. Создана базовая структура проекта со всеми необходимыми слоями
2. Добавлено развертывание приложения в Docker.
3. Реализованы ручки /info /start для ЛС, start для группы.
4. Добавлены CI actions

2023-04-28 21:24 UTC, Flash1ee commented on internal/useCase/groupUseCase.go
> +package useCase
по стилю лучше таки везде делать в snake case

2023-04-28 23:10 UTC, Flash1ee commented on .github/workflows/go.yml
> +name: Go
нужно поменять destination ветку на develop

2023-04-29 10:48 UTC, prianechka commented on .github/workflows/go.yml
> +name: Go
done

2023-04-29 10:48 UTC, prianechka commented on internal/useCase/groupUseCase.go
> +package useCase
done

2023-04-29 12:14 UTC, Flash1ee commented on .github/workflows/go.yml
> +name: Go
<img width="307" alt="Снимок экрана 2023-04-29 в 15 13 04" src="https://user-images.githubusercontent.com/55987935/235301942-472e9477-551a-45b0-8759-9586770c6c07.png">
Вот тут сделай пж просто папку useCase->usecase

файлы: group_usecase, private_usecase

2023-04-29 20:17 UTC, Flash1ee approved these changes

2023-04-29 20:36 UTC, ivaaahn requested changes

2023-04-29 20:36 UTC, ivaaahn commented on internal/server/server.go
> +		Poller: &telebot.LongPoller{Timeout: 10 * time.Second},
почему 10?

2023-04-29 20:36 UTC, ivaaahn commented on config/config.toml
> +start_port = ":8082" # Deprecated
Зочем?

2023-04-29 20:36 UTC, ivaaahn commented on config/config.go
> +
зочемм?

2023-04-29 20:43 UTC, prianechka commented on internal/server/server.go
> +		Poller: &telebot.LongPoller{Timeout: 10 * time.Second},
пока так

2023-04-29 20:43 UTC, prianechka commented on config/config.go
> +
done

2023-04-29 20:43 UTC, Flash1ee requested changes

2023-04-29 20:43 UTC, Flash1ee commented on config/config.toml
> +database = "ppo"
назови collector_bot

2023-04-29 20:43 UTC, Flash1ee commented on internal/delivery/group_handler.go
> +func MakeGroupTgHandler(log *logrus.Entry, usecase usecase.GroupUsecase) GroupHandler {
Все конструкторы через New***()

2023-04-29 20:43 UTC, Flash1ee commented on config/config.toml
> +password = "admin"
Меня напрягает, что мы пароли храним вот так.
Давай будем его передавать через переменные окружения.
Нужно создать .env файл, который передавать при запуске приложеньки.
В коде считывать так 
```
import "os"

dbPassword := os.Getenv("DB_PASSWORD")
```
Приложение запускать например, так
```
docker-compose -f docker-compose.yml --env-file ./configs/run-http.env up
```

2023-04-29 20:44 UTC, prianechka commented on config/config.toml
> +start_port = ":8082" # Deprecated
done

2023-04-29 20:46 UTC, ivaaahn approved these changes

2023-04-29 20:48 UTC, Flash1ee approved these changes

2023-04-29 20:50 UTC, merged