#2: Added mkdocs
Flash1ee/collector-telegram-bot pull request #14
Opened 2023-04-29 21:38 UTC by Flash1ee

2023-04-30 14:13 UTC, prianechka approved these changes

2023-04-30 15:52 UTC, leerycorsair approved these changes

2023-04-30 20:20 UTC, ivaaahn requested changes

2023-04-30 20:20 UTC, ivaaahn commented on .github/workflows/docs.yml
> +          python-version: 3.x
Лучше зафиксировать версию. Типа '3.10'

2023-04-30 20:20 UTC, ivaaahn commented on docs/index.md
> +collector-telegram-bot - это телеграмм бот для подсчета совместных трат между участниками группы.
телегра**м**

2023-04-30 20:20 UTC, ivaaahn commented on docs/index.md
> +* внесение трат и их описания;
внесени**я**

2023-05-01 11:04 UTC, ivaaahn approved these changes

2023-05-01 14:16 UTC, merged