#7:add sql scripts for migrations
Flash1ee/collector-telegram-bot pull request #15
Opened 2023-04-29 22:23 UTC by leerycorsair

2023-04-29 22:31 UTC, ivaaahn commented on db/02-constraints.up.sql
> +    constraint "sessions_state_check" check (state in ('active', 'closed'));
при таком раскладе есть смысл создать type session_state_type ('active', 'closed')

2023-04-29 22:33 UTC, ivaaahn requested changes

2023-04-29 22:33 UTC, ivaaahn commented on db/01-database-init.up.sql
> +    "uuid" bigserial,
почему uuid - bigserial?

2023-04-29 22:33 UTC, ivaaahn commented on db/01-database-init.up.sql
> +    "state" varchar
И вот тут тогда не varchar a session_state_type

2023-04-29 22:35 UTC, ivaaahn commented on db/02-constraints.up.sql
> +    constraint "debts_money_check" check (money > 0);
строгие неравенства точно?

2023-04-29 22:36 UTC, ivaaahn commented on db/01-database-init.up.sql
> +    "description" varchar,
агитирую за text. разницы никакой, но читается приятнее))))

2023-04-29 22:38 UTC, Flash1ee requested changes

2023-04-29 22:38 UTC, Flash1ee commented on db/01-database-init.up.sql
> +create table "sessions" (
А зачем кавычки?

2023-04-29 22:38 UTC, Flash1ee commented on db/01-database-init.up.sql
> +    "username" varchar,
Лучше вместо varchar text использовать

2023-04-29 22:38 UTC, Flash1ee commented on db/01-database-init.up.sql
> +    "description" varchar,
тут тоже text

2023-04-29 22:38 UTC, Flash1ee commented on db/02-constraints.up.sql
> +    constraint "costs_money_check" check (money > 0);
Давай ограничения и таблицы сделаем в одном файле.
Это обсуждаемо.

2023-04-29 22:38 UTC, ivaaahn commented
Не согласен с делением на два файла – миграции должны переводить БД из из консистентного состояние в консистентное. А в нашем случае если не накатим вторую, то будет плохо.

2023-04-30 12:46 UTC, leerycorsair commented on db/02-constraints.up.sql
> +    constraint "sessions_state_check" check (state in ('active', 'closed'));
Исправлено.

2023-04-30 12:46 UTC, leerycorsair commented on db/01-database-init.up.sql
> +    "state" varchar
Исправлено.

2023-04-30 12:46 UTC, leerycorsair commented on db/02-constraints.up.sql
> +    constraint "debts_money_check" check (money > 0);
Смысл учитывать нулевые затраты перевода денег?

2023-04-30 12:47 UTC, leerycorsair commented on db/01-database-init.up.sql
> +    "description" varchar,
Исправлено.

2023-04-30 12:51 UTC, leerycorsair commented on db/01-database-init.up.sql
> +create table "sessions" (
Исправлено.

2023-04-30 12:51 UTC, leerycorsair commented on db/01-database-init.up.sql
> +    "username" varchar,
Исправлено.

2023-04-30 12:51 UTC, leerycorsair commented on db/02-constraints.up.sql
> +    constraint "costs_money_check" check (money > 0);
Исправлено.

2023-04-30 13:06 UTC, leerycorsair commented on db/01-database-init.up.sql
> +    "uuid" bigserial,
Заранее решаем задачу дальнейшего масштабирования. Сессий вполне может быть более $2^32-1$.

2023-04-30 13:06 UTC, ivaaahn requested changes

2023-04-30 13:06 UTC, ivaaahn commented on db/01-database-init.up.sql
> +    "uuid" bigserial,
UUID – не число, там отдельный тип

2023-04-30 13:22 UTC, leerycorsair commented on db/01-database-init.up.sql
> +    "uuid" bigserial,
Исправлено.

2023-04-30 15:41 UTC, merged