#8: complete handlers for some actions
Flash1ee/collector-telegram-bot pull request #19
Opened 2023-04-30 15:54 UTC by prianechka

Было выполнено:
1. Реализованы команды начала сессии и добавления траты
2. Добавлены методы для репозитория, которые требуются для реализации
3. Реализованы usecase.
4. Проведено предварительное тестирование.

2023-04-30 16:33 UTC, ivaaahn requested changes

2023-04-30 16:33 UTC, ivaaahn commented on internal/delivery/group_handler.go
> +		info := dto.CreateSessionDTO{
А есть смысл добавлять DTO в нейминг, когда это понятно из пакета?

2023-04-30 16:33 UTC, ivaaahn commented on internal/delivery/group_handler.go
> +	username := c.Message().Sender.Username
Зачем эти переменные?

2023-04-30 16:33 UTC, ivaaahn commented on internal/delivery/group_handler.go
> +}
Сильная вложенность. Есть смысл делать сразу ретурн в ифах.

2023-04-30 16:33 UTC, ivaaahn commented on internal/delivery/group_handler.go
> +}
А для чего Sprintf? Просто строку нельзя передать?

2023-04-30 16:33 UTC, ivaaahn commented on internal/delivery/group_handler.go
> +}
По мне, что-то такое читается лучше

```
contextArgs := c.Args()

if len(contextArgs) != 2 {
	return c.Send("Please, create command with params /add <SessionName> <Cost>!")
}

cost, costErr := strconv.Atoi(contextArgs[1])
if costErr != nil {
	return c.Send("Cost must be integer!")
}

info := dto.AddExpenseDTO{
	ChatID:   chatID,
	Product:  contextArgs[0],
	Cost:     cost,
	UserID:   userID,
	Username: username,
}

var responseText string
err := h.usecase.AddExpenseToSession(info)
switch err {
	case usecase.SessionNotExistsErr:
		responseText = "You should start session!"
	case nil:
		responseText = "Expense is added!"
	default:
		h.log.Warnf("Create session err: %v", err)
		responseText = "Sorry, internal problems"
}

return c.Send(responseText)
```

2023-04-30 16:33 UTC, ivaaahn commented on internal/dto/add_expense_dto.go
> +type AddExpenseDTO struct {
А есть смысл добавлять DTO в нейминг, когда это понятно из пакета?

2023-04-30 16:33 UTC, ivaaahn commented on internal/dto/create_session_dto.go
> +type CreateSessionDTO struct {
А есть смысл добавлять DTO в нейминг, когда это понятно из пакета?

2023-04-30 16:33 UTC, ivaaahn commented on internal/models/connection.go
> +	db, err := sql.Open("postgres", connString)
Не будем юзать sqlx?

2023-04-30 16:33 UTC, ivaaahn commented on internal/models/member.go
> +func NewMember(sessionUUID, userID int64) *Member {
UUID != int64

2023-04-30 16:33 UTC, ivaaahn commented on internal/models/session.go
> +		State:       "active",
Разве нет принятого способа в GO сделать это константами, чтобы не было magic-strings ?

2023-04-30 16:33 UTC, ivaaahn commented on internal/repository/repository.go
> +	FROM`+" %s "+`WHERE tg_id = $1;`, UserTable)
А плюсы зачем?

2023-04-30 16:33 UTC, ivaaahn commented on internal/repository/repository.go
> +func (r *PgRepository) AddMemberToSession(sessionUUID, userID int64) error {
UUID != int64

2023-04-30 16:33 UTC, ivaaahn commented on internal/repository/repository.go
> +func (r *PgRepository) AddUserCosts(memberID int64, money int, description string) error {
Надо поправить в миграциях и сделать money там целочисленным. Я не успел владу отписать – смержили.

2023-04-30 16:33 UTC, ivaaahn commented on internal/repository/repository.go
> +func (r *PgRepository) AddUserCosts(memberID int64, money int, description string) error {
Смысла в real типе нет особо в нашем случае, копейки счиать, да еще и получать приколы вроде 102.0000013123

2023-04-30 16:33 UTC, ivaaahn commented on internal/usecase/group_usecase.go
> +	return uc.repo.AddUserCosts(memberID, info.Cost, info.Product)
Это надо в транзакцию единую

2023-04-30 16:33 UTC, ivaaahn commented on internal/usecase/group_usecase.go
> +	return uc.repo.AddMemberToSession(curSession.UUID, userID)
Это надо в транзацию

2023-04-30 16:35 UTC, prianechka commented on internal/delivery/group_handler.go
> +		info := dto.CreateSessionDTO{
да потому что по неймингу структуры должно быть понятно что она делает, а если просто Session, то не очевидно

2023-04-30 16:37 UTC, prianechka commented on internal/repository/repository.go
> +func (r *PgRepository) AddUserCosts(memberID int64, money int, description string) error {
можно просто hotfix сделать

2023-04-30 16:45 UTC, prianechka commented on internal/delivery/group_handler.go
> +}
fixed

2023-04-30 16:45 UTC, prianechka commented on internal/delivery/group_handler.go
> +	username := c.Message().Sender.Username
fixed вместе со всей функцией

2023-04-30 16:55 UTC, prianechka commented on internal/repository/repository.go
> +func (r *PgRepository) AddMemberToSession(sessionUUID, userID int64) error {
поменял на uint64

2023-04-30 18:20 UTC, ivaaahn commented on internal/repository/repository.go
> +func (r *PgRepository) AddMemberToSession(sessionUUID, userID int64) error {
UUID -- это строка специального формата https://en.wikipedia.org/wiki/Universally_unique_identifier

2023-04-30 18:20 UTC, ivaaahn commented on internal/repository/repository.go
> +func (r *PgRepository) AddMemberToSession(sessionUUID, userID int64) error {
Надо посмотреть, что в go есть для ее генерации

2023-04-30 18:20 UTC, ivaaahn commented on internal/repository/repository.go
> +func (r *PgRepository) AddUserCosts(memberID int64, money int, description string) error {
Думаю, проще в этом ПРе поменять строчку, чтобы засинхронить

2023-05-01 03:52 UTC, Flash1ee requested changes

2023-05-01 03:52 UTC, Flash1ee commented on internal/delivery/group_handler.go
> +	"collector-telegram-bot/internal/dto"
давай под каждый handler создадим отдельную папку

2023-05-01 03:52 UTC, Flash1ee commented on internal/delivery/group_handler.go
>  type GroupTgHandler struct {
Добавь в папку delivery файл contract.go, куда вынеси все интерфейсы

2023-05-01 03:52 UTC, Flash1ee commented on internal/delivery/group_handler.go
>  type GroupTgHandler struct {
```
type GroupTgHandler struct {
 	log     logger
	usecase usecase
}
```
где logger, usecase - интерфейсы из папки contact.go

2023-05-01 03:52 UTC, Flash1ee commented on internal/delivery/group_handler.go
> +		} else {
Лучше убрать else, добавить в 1 if return
Так проще код читать и структура одноуровненвая получается

2023-05-01 03:52 UTC, Flash1ee commented on internal/models/session.go
> +		State:       "active",
Принято, Саш, вынеси в константы

2023-05-01 03:52 UTC, Flash1ee commented on internal/models/connection.go
> +	db, err := sql.Open("postgres", connString)
Согласен, лучше его, проще с базой работать.

2023-05-01 03:52 UTC, Flash1ee commented on internal/usecase/group_usecase.go
То же самое, что с handler - отдельная папка на usecase и в contract.go вынести зависимости, которые есть в стрктуре

2023-05-01 03:52 UTC, Flash1ee commented on internal/usecase/group_usecase.go
>  	return &AppGroupUsecase{log: log, repo: repo}
если у тебя будет отдельный пакет, то конструктор можно просто называть New для всего: handler, usecase, repository

2023-05-01 03:52 UTC, Flash1ee commented on internal/usecase/group_usecase.go
> +	curSession, err := uc.repo.GetActiveSessionByChatID(info.ChatID)
Лучше конечно сначала проверять сессию, чтобы в базу лишний раз не писать.
Даже если юзер будет использоваться, а если не будет?

2023-05-01 03:52 UTC, Flash1ee commented on internal/repository/repository.go
> +		($1, $2, current_date, $3);`, UserTable)
ты можешь добавить returning id и в usecase GetUser еще раз не дергать GetUser, чтобы отдать его id

2023-05-01 11:48 UTC, prianechka commented on internal/repository/repository.go
> +	FROM`+" %s "+`WHERE tg_id = $1;`, UserTable)
там конкатенация строк, го не компилит с %s в строке ``, а кавычки нужны для того, чтобы сделать многострочную строку

2023-05-01 13:14 UTC, Flash1ee approved these changes

2023-05-01 13:37 UTC, ivaaahn approved these changes

2023-05-01 13:39 UTC, merged